name: laundry_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  shared_preferences: ^2.0.7
  google_fonts: ^6.0.0
  http: ^1.1.0

dev_dependencies: 
  build_runner: ^2.1.8
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/user_image.jpg

